### ISSUE TITLE
cpp跟lpython在某些情况下，并不一致

### ISSUE THREAD

**Issue by l2009312042** [xiaominfc/melspectrogram_cpp#1]
CFFT::Forward(pSignal,n_fft)这个函数导致。
在n_fft不是512 ，1024 这类数时，存在不一致，比如n_fft为400时

**Comment by minchaoyue** [comment]
你好，目前也在看这段代码，窗长度除了改n_fft   在函数hanning_w(n_fft,window); 中，还需要改那里？ 比如 hanning_w(640 ,window); 目前代码crash.

谢谢

**Comment by xiaominfc** [comment]
已修复 通过fftw兼容
